server:
  port: 8080
hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 300m
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /items/**
      - /hi